//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antrian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntrianPelayanan
    {
        public string KodeAntrian { get; set; }
        public Nullable<int> Bidang { get; set; }
        public Nullable<int> Pelayanan { get; set; }
        public string Status { get; set; }
        public Nullable<int> Loket { get; set; }
        public string NoAntrian { get; set; }
    
        public virtual BidangPelayanan BidangPelayanan { get; set; }
        public virtual Pelayanan Pelayanan1 { get; set; }
    }
}
